#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $DOTFILES
for folder in $FOLDERS; do
    stow -D $folder
done
for folder in $FOLDERS
do
    echo "stow $folder"
    stow $folder
done
popd
